App_Login/urls.py
from django.urls import path
from App_Login import views

app_name= 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('change-password/', views.pass_change, name='pass_change'),
]

api/urls.py
from django.urls import path
from api import views

app_name='api'

urlpatterns = [
    path('',views.ButtonView.as_view(),name='all_options'),
    path('get_data',views.getDataList, name='get_data'),
    path('export_to_json',views.exportDataToJson, name='export_to_json'),
    path('post_data/',views.postData, name='post_data'),
    path('delete/<pk>/', views.TaskDeleteAPIView.as_view(), name='delete'),
    path('task/<pk>/', views.TaskSingleView.as_view(), name='task'),
    path('update/<pk>/', views.TaskUpdateAPIView.as_view(), name='update'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

# display media/ image
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Login.urls')),
    path('accounts/', include('App_Login.urls')),
    path('tasks/', include('tasks.urls')),
    path('api/', include('api.urls')),
]


# media / image
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tasks/urls.py
# tasks\urls.py
from django.urls import path
from tasks import views


app_name = 'tasks'



urlpatterns = [
    path('', views.TaskListView.as_view(), name='task_list'),
    path('task_detail_view/<pk>/', views.TaskDetailView.as_view(), name='task_detail'),  
    path('create_task/',views.CreateNewTaskView.as_view(), name='create_task'),
    path('update_task/<pk>/',views.TaskUpdateView.as_view(), name='update_task'),
    path('task_delete/<pk>/', views.TaskDeleteView.as_view(), name='task_delete'),
    path('add_image/<pk>/', views.add_image_to_task, name='add_image_to_task'),


    path('delete_image/<pk>/', views.DeleteImageView.as_view(), name='delete_image'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">


    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    
    
    <!-- popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js" integrity="sha512-TPh2Oxlg1zp+kz3nFA0C5vVC6leG/6mm1z9+mA81MI5eaUVqasPLO8Cuk4gMF4gUfP5etR73rgU/8PNMsSesoQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <!-- fontawesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Bootstrap DateTimePicker CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet">

  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



  {% comment %}  {% endcomment %}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  {% comment %}  {% endcomment %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    {% comment %}  {% endcomment %}






   {% comment %} main part {% endcomment %}
    <title>{% block title_block %} Task Manager {% endblock %}</title>

    {% block css_block %}

    {% endblock %}

</head>
<body>
    
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item-active">
                {% comment %} a class="nav-link" href="{% url 'index' %}"> {% endcomment %}
                <a class="nav-link" href="{% url 'tasks:task_list' %}">
                    Home
                </a>
                
            </li>
            {%endif%}

             <!-- dropdown navigation bar on username-->
            {% if user.is_authenticated %}
                <div clas='nav-item dropdown'>
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        @{{user.username}}
                    </a>
                
                    <!-- menu items in drop down -->
                    <div class="dropdown-menu">
                        
                        
                        <a class="dropdown-item" href="{% url 'App_Login:pass_change' %}">Change Password</a>
                        
                        <hr>
                        <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a> 
                        
                    </div>

                </div>


            {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
                </li>

            {% endif %}
            
        </ul>

       


    </nav>

    <div class="container" style="padding-top:20px">

        {% block body_block %}

        {% endblock %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>




    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

</body>
</html>