api/urls.py
from django.urls import path
from api import views

app_name='api'

urlpatterns = [
    path('',views.ButtonView.as_view(),name='all_options'),
    path('get_data',views.getDataList, name='get_data'),
    path('export_to_json',views.exportDataToJson, name='export_to_json'),
    path('post_data/',views.postData, name='post_data'),
    path('delete/<pk>/', views.TaskDeleteAPIView.as_view(), name='delete'),
    path('task/<pk>/', views.TaskSingleView.as_view(), name='task'),
    path('update/<pk>/', views.TaskUpdateAPIView.as_view(), name='update'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

# display media/ image
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Login.urls')),
    path('accounts/', include('App_Login.urls')),
    path('tasks/', include('tasks.urls')),
    path('api/', include('api.urls')),
]


# media / image
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tasks/urls.py
# tasks\urls.py
from django.urls import path
from tasks import views


app_name = 'tasks'



urlpatterns = [
    path('', views.TaskListView.as_view(), name='task_list'),
    path('task_detail_view/<pk>/', views.TaskDetailView.as_view(), name='task_detail'),  
    path('create_task/',views.CreateNewTaskView.as_view(), name='create_task'),
    path('update_task/<pk>/',views.TaskUpdateView.as_view(), name='update_task'),
    path('task_delete/<pk>/', views.TaskDeleteView.as_view(), name='task_delete'),
    path('add_image/<pk>/', views.add_image_to_task, name='add_image_to_task'),


    path('delete_image/<pk>/', views.DeleteImageView.as_view(), name='delete_image'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


    


class Task(models.Model):

    LOW = 1
    MEDIUM = 2
    HIGH = 3
    
    PRIORITY_CHOICES = [
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='task_user')
    title = models.CharField(max_length=264,  blank= False)
    description = models.TextField(blank=True)
    due_date = models.DateField(blank=False)
    #images = models.ImageField(upload_to='photos/')
    # images = models.ManyToManyField(Image, blank=True)
    priority = models.IntegerField(choices=PRIORITY_CHOICES)
  
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    is_complete = models.BooleanField(default=False)

    class Meta:
        ordering = ['-priority', 'due_date']

    def __str__(self):
        return str(self.title)
    


class Images(models.Model):
    task =  models.ForeignKey(Task, on_delete=models.CASCADE, related_name='image_task')
    image = models.ImageField(upload_to='photos/')

    def __str__(self):
        return str(self.image) 
 

tasks/forms.py
# tasks\forms.py
from django import forms
from tasks.models import Task, Images

# class MultipleFileInput(forms.ClearableFileInput):
#     allow_multiple_selected = True


class CreateTaskForm(forms.ModelForm):
   
    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'priority']


class TaskListForm(forms.ModelForm):
    class Meta:
        model = Task
        fields= ['title','priority','due_date']


class UpdateTaskForm(forms.ModelForm):
   
    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'priority' , 'is_complete']
        labels = {
            'is_complete': 'Mark as Complete', 
        }


class CreateImageForm(forms.ModelForm):
    class Meta:
        model= Images
        fields=['image']

tasks/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from tasks.forms import CreateTaskForm, TaskListForm, UpdateTaskForm, CreateImageForm
from tasks.models import Task, Images
from django.views.generic import CreateView, UpdateView, ListView, DetailView, View, TemplateView, DeleteView

from django.db.models import Q
from datetime import datetime
from django.utils import timezone



class CreateNewTaskView(CreateView):
    model = Task
    form_class = CreateTaskForm
    template_name = 'tasks/create_tasks.html'  
    success_url = reverse_lazy('tasks:create_task')

    def form_valid(self, form):
        # current user
        user = self.request.user
        # Assign the current user to the user field of the Task instance
        form.instance.user = user
        # Call the parent class's form_valid() method to save the form
        return super().form_valid(form)
    
#####################################################################################
# class TaskListView(ListView):
#     model = Task
#     form_class = TaskListForm
#     template_name = 'tasks/task_list.html'

#     def get_queryset(self):
#         user = self.request.user
#         queryset = Task.objects.filter(user=user)
        
    
#          # Search functionality
#         search = self.request.GET.get('search', '').strip()
#         if search:
#             queryset = queryset.filter(title__icontains=search)

#         return queryset


class TaskListView(ListView):
    model = Task
    form_class = TaskListForm
    template_name = 'tasks/task_list.html'

    def get_queryset(self):
        user = self.request.user
        queryset = Task.objects.filter(user=user)

        # Search functionality
        search_query = self.request.GET.get('search', '').strip()
        filter_criteria = self.request.GET.get('filter_criteria')
        filter_value = self.request.GET.get('filter_value')

        if search_query:
            queryset = queryset.filter(title__icontains=search_query)

        if filter_criteria and filter_value:
            filter_criteria_mapping = {
                'title': 'title__icontains',
                'creation_date': 'upload_date',
                'due_date': 'due_date',
                'priority': 'priority',
                'is_complete': 'is_complete',
            }
            filter_param = filter_criteria_mapping.get(filter_criteria)
            if filter_param:
                try:
                    if filter_criteria == 'is_complete':
                        filter_value = bool(filter_value.lower() in ['true', '1', 'yes'])
                    elif filter_criteria == 'priority':
                        priority_mapping = {
                            'high': Task.HIGH,
                            'medium': Task.MEDIUM,
                            'low': Task.LOW,
                        }
                        filter_value = priority_mapping.get(filter_value.lower())
                    queryset = queryset.filter(**{filter_param: filter_value})
                except Exception as e:
                    # Handle the error gracefully, e.g., log it
                    pass

        return queryset
###########################################################################
class TaskDetailView(DetailView):
    model = Task
    template_name = 'tasks/detail_task.html'
    context_object_name = 'Task'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = self.get_object()
        context['images'] = task.image_task.all()  # Fetch all images related to the task
        return context


class TaskUpdateView(UpdateView):
    model = Task
    form_class = UpdateTaskForm
    template_name = 'tasks/update_task.html'
    context_object_name = 'Task'
    success_url = reverse_lazy('tasks:task_list')


class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'tasks/task_confirm_delete.html'  
    context_object_name = 'Task'
    success_url = reverse_lazy('tasks:task_list')  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Confirm Deletion'
        return context
    

# add image
def add_image_to_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        form = CreateImageForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.task = task
            image.save()
            return redirect('tasks:task_detail', pk=pk)
    else:
        form = CreateImageForm()
    return render(request, 'tasks/add_image_to_task.html', {'form': form, 'task': task})



# image detail

class DeleteImageView(DeleteView):
    model = Images
    template_name = 'tasks/image_confirm_delete.html'  
    context_object_name = 'image'
    # success_url = reverse_lazy('tasks:task_list')  
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Confirm Deletion'
        return context
    
    def get_success_url(self):
        # Access the task's primary key (task.pk) associated with the image
        task_pk = self.object.task.pk
        
        return reverse_lazy('tasks:task_detail', kwargs={'pk': task_pk})

templates/tasks/add_image_to_task.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title_block %} Add Image {% endblock %}

{% block body_block %}

    <h3>Add image</h3>

    <form method="post" enctype='multipart/form-data'>
        {{ form|crispy }}
        {% csrf_token %}

        <button type="submit" class="btn btn-primary btn-md">Add Image</button>
       
    </form>

{% endblock %}

templates/tasks/create_tasks.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title_block %} Create Task {% endblock %}

{% block body_block %}

    <h3>Create Task</h3>

    <form method="post" enctype='multipart/form-data'>
        {{ form|crispy }}
        {% csrf_token %}

        <button type="submit" class="btn btn-primary btn-md">Create Task</button>
       
    </form>
    <br>
    <br>

    <script>
        flatpickr("#id_due_date", {
            dateFormat: 'Y-m-d',
            // Add any additional options here
          });
      </script>

{% endblock %}

templates/tasks/detail_task.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% comment %} {% block title_block %} Task List {% endblock %} {% endcomment %}

{% block css_block %}

    <style>
        .addButton {
            position: fixed;
            bottom: 45px;
            right: 55px;
            font-size: large;
            padding: 1rem;
            font-weight: bold;
            background-color: rgb(22, 111, 228);
            border-radius: 10px;
            cursor: pointer;      
        }

        .addButton a{
            decoration: none; 
            color: inherit;      
        }


        .image-container {
            display: inline-block;
            position: relative;
            border: 3px solid black; 
            margin: 5px;
        }
        .delete-icon {
            position: absolute;
            top: 5px;
            right: 5px;
            cursor: pointer;
            color: red;
        }
    </style>
{% endblock %}

{% block body_block %}
    
        <center>
            <h3>{{Task.title}}</h3>
        </center>
        <br>
        <p><strong>Description: </strong>{{Task.description|linebreaks}}</p>
        <p><strong>Due: </strong>{{Task.due_date}}</p>
        
        <br>


        {% comment %}  {% endcomment %}
        {% for image in images %}
            <a class="image-container" href ="{% url 'tasks:delete_image' pk=image.pk %}">
                <img src="/media/{{ image }}" width="200px" height="150px">
            </a>   
        {% endfor %}
        <p style="color:red"><strong>click any image to view or delete it</strong></p>

        <a class="btn btn-success" href="{% url 'tasks:add_image_to_task' pk=Task.pk %}">Add Image</a>
       
        <br>
        <br>

        <p><strong>Priority: </strong>{{Task.get_priority_display}}</p>
        <p><strong>Upload Date: </strong>{{Task.upload_date}}</p>
        <p><strong>Last Update: </strong>{{Task.update_date}}</p>
        
        {% if Task.is_complete == False %}
            <p><strong>Task Status: </strong><strong style="color:red">Incomplete</strong></p>
        {% else %}
            <p><strong>Task Status: </strong><strong style="color:green">Completed</strong></p>
        {% endif %}

        <button class="addButton">
            <a href="{% url 'tasks:update_task' pk=Task.pk %}">Update Task</a>
        </button>
        <br>

        <a class="btn btn-danger" href="{% url 'tasks:task_delete' pk=Task.pk %}">Delete Task</a>
        <br>
        <br>

  
{% endblock %}
    


        
        
    

templates/tasks/image_confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% comment %} {% block title_block %} Task List {% endblock %} {% endcomment %}

{% block css_block %}

{% endblock %}

{% block body_block %}
  <center>
  <img src="/media/{{image}}" height="350px" width="500px" style="border:5px solid black"/>"
  <br>
  <br>
  <p><strong>Are you sure you want to delete the image?</strong></p>
  <br>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirm Delete</button>
    <a href="{% url 'tasks:task_detail' pk=image.task.pk %}" class="btn btn-secondary">Cancel</a>
  </form>
</center>

  
{% endblock %}
    


        
        
    

templates/tasks/task_confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% comment %} {% block title_block %} Task List {% endblock %} {% endcomment %}

{% block css_block %}

{% endblock %}

{% block body_block %}
    
  <h4>{{ Task.title }}</h4>
  <p>Are you sure you want to delete the task "{{ Task }}"?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirm Delete</button>
    <a href="{% url 'tasks:task_list' %}" class="btn btn-secondary">Cancel</a>
  </form>

  
{% endblock %}
    


        
        
    

templates/tasks/task_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block title_block %} Task List {% endblock %}

{% block css_block %}

    <style>

        .addButton {
            position: fixed;
            bottom: 45px;
            right: 55px;
            font-size: large;
            padding: 1rem;
            font-weight: bold;
            background-color: rgb(22, 111, 228);
            border-radius: 10px;
            cursor: pointer;      
        }

        .addButton a{
            decoration: none; 
            color: inherit;      
        }






        .list-view-custom-style{
            text-align: left;
        }
        .list-view-custom-style:hover{
            background-color: blue;
            color: white;
            text-decoration: none;
        }
        {% comment %}  /* inherit== Use the color of the parent element */{% endcomment %}
        a {
            color: inherit; 
            text-decoration: none; 
        }
    </style>
{% endblock %}

{% block body_block %}
    <center>
        <h3>Task List</h3>
        
        <center>
        <form class="form-inline" method="GET">
            <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search Task">
            <br>

            {% comment %} select {% endcomment %}
            <select class="form-control mr-sm-2" name="filter_criteria">
                {% comment %} <option value="title">Title</option> {% endcomment %}
                <option value="creation_date">Creation Date</option>
                <option value="due_date">Due Date</option>
                <option value="priority">Priority</option>
                <option value="is_complete">Completion Status</option>
            </select>
            <input class="form-control mr-sm-2" type="text" name="filter_value" placeholder="Filter Value">

            {% comment %}  {% endcomment %}


            <button class="btn btn-success" type="submit">Search</button>
        </form>   
    </center>
    <br>

    <p style="color: red">Note: date filter format is YYYY-MM-DD, like 2024-01-30<p>
   
    {%for data in object_list %}
        <ul class="list-group">
            <a href="{% url 'tasks:task_detail' pk=data.pk %}">
                <li class="list-group-item list-view-custom-style">
                    <p><h4>{{data.title}}</h4></p>
                    <p>Priority: {{data.get_priority_display}}</p>
                    <p>Due: {{data.due_date}}</p>
                </li>
            </a>
        </ul>
    {%endfor%}


    <button class="addButton">
        <a href="{% url 'tasks:create_task'%}">Add New Task</a>
    </button>



        
        
    
<br>
<a href="{% url 'api:all_options' %}" class="btn btn-success btn-lg">API view</a>
<br>
<br>

{% endblock %}

templates/tasks/update_task.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title_block %} Create Task {% endblock %}

{% block body_block %}

    <h3>Update Task</h3>

    <form method="post" enctype='multipart/form-data'>
        {{ form|crispy }}
        {% csrf_token %}

        <button type="submit" class="btn btn-primary btn-md">Update Task</button>
       
    </form>
    <br>
    <br>

    <script>
        flatpickr("#id_due_date", {
            dateFormat: 'Y-m-d',
            // Add any additional options here
          });
      </script>

{% endblock %}